title: Azamat Li, full lifecycle developer
description: > Laravel & SPA stack dev portfolio
  <br><br>
  Second description 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
